import { Ticket, Customer, Product, Review, SlaRule } from './types';

export const INITIAL_TICKETS: Ticket[] = [
  {
    id: 'TK-9021',
    subject: 'Product Issue on ThinkPad X1 Carbon keyboard lag',
    customer: 'Acme Corp',
    status: 'OPEN',
    priority: 'HIGH',
    lastUpdated: '3m ago',
    department: 'L1 Support',
    date: '2024-03-15',
  },
  {
    id: 'TK-9020',
    subject: 'Billing Inquiry for Premier Premium Onsite warranty renewal',
    customer: 'Globex Inc',
    status: 'PENDING',
    priority: 'MEDIUM',
    lastUpdated: '1h ago',
    department: 'Billing',
    date: '2024-03-15',
  },
  {
    id: 'TK-9019',
    subject: 'Feature Request by Vantage software developer group integration',
    customer: 'Soylent Corp',
    status: 'RESOLVED',
    priority: 'LOW',
    lastUpdated: '4h ago',
    department: 'Enterprise',
    date: '2024-03-14',
  },
  {
    id: 'TK-9018',
    subject: 'Feature Request by internal QA for Yoga Book dual display drivers',
    customer: 'Soylent Corp',
    status: 'RESOLVED',
    priority: 'LOW',
    lastUpdated: '4h ago',
    department: 'L2 Technical',
    date: '2024-03-14',
  },
  {
    id: 'TK-9017',
    subject: 'Feature Request by Legion Pro gaming bios overclock support',
    customer: 'Soylent Corp',
    status: 'RESOLVED',
    priority: 'LOW',
    lastUpdated: '4h ago',
    department: 'L2 Technical',
    date: '2024-03-14',
  },
  {
    id: 'TK-9026',
    subject: 'Product Issue on ThinkCentre M90q PXE boot failure',
    customer: 'Acme Corp',
    status: 'OPEN',
    priority: 'HIGH',
    lastUpdated: '3h ago',
    department: 'L1 Support',
    date: '2024-03-14',
  },
  {
    id: 'TK-9023',
    subject: 'Product Issue with Legion Pro overheating under sustained workload',
    customer: 'Acme Corp',
    status: 'PENDING',
    priority: 'MEDIUM',
    lastUpdated: '1h ago',
    department: 'L1 Support',
    date: '2024-03-13',
  },
  {
    id: 'TK-9022',
    subject: 'Billing Inquiry for bulk AMC license package',
    customer: 'Globex Inc',
    status: 'PENDING',
    priority: 'MEDIUM',
    lastUpdated: '1h ago',
    department: 'Billing',
    date: '2024-03-13',
  },
  {
    id: 'TK-9010',
    subject: 'Feature Request by Enterprise clients for fleet firmware automation',
    customer: 'Globex Inc',
    status: 'PENDING',
    priority: 'MEDIUM',
    lastUpdated: '1h ago',
    department: 'Enterprise',
    date: '2024-03-13',
  },
  {
    id: 'TK-9014',
    subject: 'Billing Inquiry on ThinkStation P620 custom configuration',
    customer: 'Globex Inc',
    status: 'RESOLVED',
    priority: 'LOW',
    lastUpdated: '1h ago',
    department: 'Billing',
    date: '2024-03-12',
  },
  {
    id: 'TK-9013',
    subject: 'Feature Request by Yoga 9i users to enable haptic feedback presets',
    customer: 'Soylent Corp',
    status: 'RESOLVED',
    priority: 'LOW',
    lastUpdated: '1h ago',
    department: 'L2 Technical',
    date: '2024-03-12',
  },
  {
    id: 'TK-9012',
    subject: 'Product Issue on ThinkPad L14 secure boot keys mismatch',
    customer: 'Globex Inc',
    status: 'RESOLVED',
    priority: 'LOW',
    lastUpdated: '1h ago',
    department: 'L1 Support',
    date: '2024-03-12',
  },
  {
    id: 'TK-9015',
    subject: 'Billing Inquiry for enterprise support dispatch excess invoice',
    customer: 'Globex Inc',
    status: 'PENDING',
    priority: 'MEDIUM',
    lastUpdated: '1h ago',
    department: 'Billing',
    date: '2024-03-11',
  },
  {
    id: 'TK-9016',
    subject: 'Product Issue with Premier Support dispatch delays in EU',
    customer: 'Acme Corp',
    status: 'RESOLVED',
    priority: 'LOW',
    lastUpdated: '3h ago',
    department: 'Enterprise',
    date: '2024-03-11',
  },
  {
    id: 'TK-9008',
    subject: 'Product Inquiry on upcoming Lenovo AI Copilot integrations',
    customer: 'Inotech',
    status: 'OPEN',
    priority: 'HIGH',
    lastUpdated: '3m ago',
    department: 'Enterprise',
    date: '2024-03-10',
  },
  {
    id: 'TK-9005',
    subject: 'Lenovo Vantage software suite crashes after Windows update',
    customer: 'Inotech',
    status: 'OPEN',
    priority: 'CRITICAL',
    lastUpdated: '2h ago',
    department: 'L2 Technical',
    date: '2024-03-10',
  },
  {
    id: 'TK-9004',
    subject: 'Legion Toolkit thermal configuration mismatch',
    customer: 'Vertex Group',
    status: 'ESCALATED',
    priority: 'CRITICAL',
    lastUpdated: '5m ago',
    department: 'L2 Technical',
    date: '2024-03-09',
  },
  {
    id: 'TK-9003',
    subject: 'SLA Breach notification - ThinkPad carbon battery swell batch query',
    customer: 'TechNova',
    status: 'ESCALATED',
    priority: 'CRITICAL',
    lastUpdated: '10m ago',
    department: 'Enterprise',
    date: '2024-03-08',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'CID-1001',
    name: 'Acme Corp',
    contactPerson: 'J. Doe',
    location: 'New York',
    productsOwned: 3,
    openTickets: 3,
    plan: 'PREMIUM',
    industry: 'Technology',
    status: 'ACTIVE',
    email: 'j.doe@acme.com',
  },
  {
    id: 'CID-1002',
    name: 'Globex Inc',
    contactPerson: 'K. Smith',
    location: 'San Francisco',
    productsOwned: 2,
    openTickets: 1,
    plan: 'STANDARD',
    industry: 'Financial Services',
    status: 'ACTIVE',
    email: 'k.smith@globex.com',
  },
  {
    id: 'CID-1003',
    name: 'Soylent Corp',
    contactPerson: 'L. Green',
    location: 'Chicago',
    productsOwned: 1,
    openTickets: 0,
    plan: 'FREE',
    industry: 'Healthcare',
    status: 'INACTIVE',
    email: 'l.green@soylent.com',
  },
  {
    id: 'CID-1004',
    name: 'Inotech',
    contactPerson: 'L. Green',
    location: 'Chicago',
    productsOwned: 1,
    openTickets: 0,
    plan: 'FREE',
    industry: 'Manufacturing',
    status: 'ACTIVE',
    email: 'tech@inotech.com',
  },
  {
    id: 'CID-1005',
    name: 'Vertex Group',
    contactPerson: 'M. Vance',
    location: 'Boston',
    productsOwned: 4,
    openTickets: 2,
    plan: 'PREMIUM',
    industry: 'Consulting',
    status: 'ACTIVE',
    email: 'm.vance@vertex.com',
  },
  {
    id: 'CID-1006',
    name: 'TechNova',
    contactPerson: 'A. Stark',
    location: 'Seattle',
    productsOwned: 5,
    openTickets: 1,
    plan: 'PREMIUM',
    industry: 'Aerospace',
    status: 'AT RISK',
    email: 'a.stark@technova.com',
  },
  {
    id: 'CID-1007',
    name: 'Delta Systems',
    contactPerson: 'P. Parker',
    location: 'Queens',
    productsOwned: 2,
    openTickets: 1,
    plan: 'STANDARD',
    industry: 'Education',
    status: 'ACTIVE',
    email: 'p.parker@delta.edu',
  },
  {
    id: 'CID-1008',
    name: 'CyberDyne',
    contactPerson: 'J. Connor',
    location: 'Los Angeles',
    productsOwned: 8,
    openTickets: 4,
    plan: 'PREMIUM',
    industry: 'Defense',
    status: 'AT RISK',
    email: 'j.connor@cyberdyne.com',
  },
  {
    id: 'CID-1009',
    name: 'Hooli Inc',
    contactPerson: 'G. Belson',
    location: 'Palo Alto',
    productsOwned: 3,
    openTickets: 0,
    plan: 'STANDARD',
    industry: 'Technology',
    status: 'INACTIVE',
    email: 'gavin@hooli.xyz',
  },
  {
    id: 'CID-1010',
    name: 'Initech Labs',
    contactPerson: 'P. Gibbons',
    location: 'Austin',
    productsOwned: 2,
    openTickets: 0,
    plan: 'FREE',
    industry: 'Retail',
    status: 'ACTIVE',
    email: 'pgibbons@initech.com',
  }
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'PID-2001',
    name: 'ThinkPad X1 Carbon Gen 12',
    category: 'Electronics',
    activeCustomers: 430,
    warrantyCoverage: 85,
    amcCoverage: 60,
    modelSeries: 'ThinkPad X Series',
    releaseYear: 2024,
  },
  {
    id: 'PID-2002',
    name: 'Legion Pro 7i Gen 9',
    category: 'Electronics',
    activeCustomers: 215,
    warrantyCoverage: 90,
    amcCoverage: 75,
    modelSeries: 'Legion Series',
    releaseYear: 2024,
  },
  {
    id: 'PID-2003',
    name: 'Lenovo Vantage Enterprise Suite',
    category: 'Software',
    activeCustomers: 640,
    warrantyCoverage: 98,
    amcCoverage: 95,
    modelSeries: 'Vantage Series',
    releaseYear: 2023,
  },
  {
    id: 'PID-2004',
    name: 'Yoga Book 9i Dual Screen',
    category: 'Electronics',
    activeCustomers: 120,
    warrantyCoverage: 82,
    amcCoverage: 50,
    modelSeries: 'Yoga Series',
    releaseYear: 2023,
  },
  {
    id: 'PID-2005',
    name: 'ThinkCentre M90q Tiny Desktop',
    category: 'Electronics',
    activeCustomers: 310,
    warrantyCoverage: 88,
    amcCoverage: 80,
    modelSeries: 'ThinkCentre M Series',
    releaseYear: 2024,
  },
  {
    id: 'PID-2006',
    name: 'Lenovo Premier Support Plus',
    category: 'Services',
    activeCustomers: 850,
    warrantyCoverage: 100,
    amcCoverage: 100,
    modelSeries: 'Premier Support',
    releaseYear: 2022,
  },
  {
    id: 'PID-2007',
    name: 'IdeaPad Slim 5 Pro AMD',
    category: 'Electronics',
    activeCustomers: 512,
    warrantyCoverage: 75,
    amcCoverage: 40,
    modelSeries: 'IdeaPad Series',
    releaseYear: 2023,
  },
  {
    id: 'PID-2008',
    name: 'ThinkStation P620 Workstation',
    category: 'Electronics',
    activeCustomers: 180,
    warrantyCoverage: 95,
    amcCoverage: 85,
    modelSeries: 'ThinkStation Series',
    releaseYear: 2022,
  },
  {
    id: 'PID-2009',
    name: 'Lenovo Cloud Fleet Manager',
    category: 'Software',
    activeCustomers: 340,
    warrantyCoverage: 95,
    amcCoverage: 90,
    modelSeries: 'Cloud Manager',
    releaseYear: 2023,
  },
  {
    id: 'PID-2010',
    name: 'Lenovo Smart AMC Service',
    category: 'Services',
    activeCustomers: 490,
    warrantyCoverage: 92,
    amcCoverage: 100,
    modelSeries: 'Smart AMC',
    releaseYear: 2024,
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'FR-5001',
    customer: 'Acme Corp',
    ticketId: 'TK-9021',
    rating: 5,
    comment: 'Excellent support for Lenovo ThinkPad X1 Carbon. Technical engineer repaired keyboard onsite within 4 hours!',
    date: '2024-03-15',
  },
  {
    id: 'FR-5002',
    customer: 'Globex Inc',
    ticketId: 'TK-9020',
    rating: 5,
    comment: 'Excellent billing support for Lenovo Premier support. Smooth billing and subscription extensions.',
    date: '2024-03-15',
  },
  {
    id: 'FR-5003',
    customer: 'Soylent Corp',
    ticketId: 'TK-9019',
    rating: 2,
    comment: 'Billing dispute took too long. First levels kept routing to regional teams instead of solving it immediately.',
    date: '2024-03-14',
  },
  {
    id: 'FR-5004',
    customer: 'Soylent Corp',
    ticketId: 'TK-9018',
    rating: 2,
    comment: 'Display firmware update query response took 3 business days. Need faster L2 ticketing response times.',
    date: '2024-03-14',
  },
  {
    id: 'FR-5005',
    customer: 'Acme Corp',
    ticketId: 'TK-9017',
    rating: 5,
    comment: 'Superb turnaround on BIOS overclocking patch testing. Engineering team is extremely responsive for Legion.',
    date: '2024-03-14',
  },
  {
    id: 'FR-5006',
    customer: 'Globex Inc',
    ticketId: 'TK-9026',
    rating: 5,
    comment: 'Onsite dispatch of tiny fan parts was flawless. ThinkCentre is running cool again. Highly recommended service.',
    date: '2024-03-14',
  },
  {
    id: 'FR-5007',
    customer: 'Soylent Corp',
    ticketId: 'TK-9019',
    rating: 4,
    comment: 'Excellent technical answers on Lenovo System Update deployment. Smooth SCCM catalog catalogs.',
    date: '2024-03-14',
  },
  {
    id: 'FR-5008',
    customer: 'Globex Inc',
    ticketId: 'TK-9013',
    rating: 2,
    comment: 'Customer dispute about additional repair pricing took too long. Escalated to manager before response received.',
    date: '2024-03-14',
  },
  {
    id: 'FR-5009',
    customer: 'Inotech',
    ticketId: 'TK-9018',
    rating: 5,
    comment: 'Extremely polite engineers. They helped diagnose motherboard issue on Yoga Book over remote link immediately.',
    date: '2024-03-15',
  },
];

export const INITIAL_SLA_RULES: SlaRule[] = [
  {
    id: 'SLA-001',
    ruleName: 'L1 Initial Support Response Time SLA',
    department: 'L1 Support',
    condition: 'Resolution Time',
    priority: 'CRITICAL',
    resolutionTime: '4h',
    notification: '[Notify L1 Team]',
    status: 'ENABLED',
  },
  {
    id: 'SLA-002',
    ruleName: 'L2 Complex Issue Resolution Timeline',
    department: 'L2 Technical',
    condition: 'Resolution Time',
    priority: 'CRITICAL',
    resolutionTime: '4h',
    notification: '[Notify L1 Team]',
    status: 'ENABLED',
  },
  {
    id: 'SLA-003',
    ruleName: 'General L2 Normal Flow Escalation',
    department: 'L2 Technical',
    condition: 'Resolution Time',
    priority: 'HIGH',
    resolutionTime: '24h',
    notification: '[Notify L1 Team]',
    status: 'ENABLED',
  },
  {
    id: 'SLA-004',
    ruleName: 'L1 High Severity Escalate To Lead',
    department: 'L1 Support',
    condition: 'Resolution Time',
    priority: 'HIGH',
    resolutionTime: '24h',
    notification: '[Notify L2 Team]',
    status: 'ENABLED',
  },
  {
    id: 'SLA-005',
    ruleName: 'Billing Disputes Settlement Standard',
    department: 'Billing',
    condition: 'Resolution Time',
    priority: 'MEDIUM',
    resolutionTime: '48h',
    notification: '[Notify L2 Team]',
    status: 'DISABLED',
  },
  {
    id: 'SLA-006',
    ruleName: 'Billing General Query Answering Time',
    department: 'Billing',
    condition: 'Resolution Time',
    priority: 'MEDIUM',
    resolutionTime: '48h',
    notification: '[Notify Billing]',
    status: 'DISABLED',
  },
  {
    id: 'SLA-007',
    ruleName: 'Enterprise VIP Accounts SLA Response Cover',
    department: 'Billing',
    condition: 'Resolution Time',
    priority: 'MEDIUM',
    resolutionTime: '48h',
    notification: '[Notify Billing]',
    status: 'DISABLED',
  },
  {
    id: 'SLA-008',
    ruleName: 'Enterprise Technical Incident Standard SLA',
    department: 'Billing',
    condition: 'Resolution Time',
    priority: 'MEDIUM',
    resolutionTime: '48h',
    notification: '[Notify Billing]',
    status: 'DISABLED',
  },
];
