import { Ticket, Customer, Product, Review, SlaRule } from './types';

export const INITIAL_TICKETS: Ticket[] = [
  {
    id: 'TK-9021',
    subject: 'Product Issue on ThinkPad X1 Carbon keyboard lag',
    customer: 'Acme Corp',
    status: 'OPEN',
    priority: 'HIGH',
    lastUpdated: '3m ago',
    department: 'L1 Support',
    date: '2024-03-15',
  },
  {
    id: 'TK-9020',
    subject: 'Billing Inquiry for Premier Premium Onsite warranty renewal',
    customer: 'Globex Inc',
    status: 'PENDING',
    priority: 'MEDIUM',
    lastUpdated: '1h ago',
    department: 'Billing',
    date: '2024-03-15',
  },
  {
    id: 'TK-9019',
    subject: 'Feature Request by Vantage software developer group integration',
    customer: 'Soylent Corp',
    status: 'RESOLVED',
    priority: 'LOW',
    lastUpdated: '4h ago',
    department: 'Enterprise',
    date: '2024-03-14',
  },
  {
    id: 'TK-9018',
    subject: 'Feature Request by internal QA for Yoga Book dual display drivers',
    customer: 'Soylent Corp',
    status: 'RESOLVED',
    priority: 'LOW',
    lastUpdated: '4h ago',
    department: 'L2 Technical',
    date: '2024-03-14',
  },
  {
    id: 'TK-9017',
    subject: 'Feature Request by Legion Pro gaming bios overclock support',
    customer: 'Soylent Corp',
    status: 'RESOLVED',
    priority: 'LOW',
    lastUpdated: '4h ago',
    department: 'L2 Technical',
    date: '2024-03-14',
  },
  {
    id: 'TK-9026',
    subject: 'Product Issue on ThinkCentre M90q PXE boot failure',
    customer: 'Acme Corp',
    status: 'OPEN',
    priority: 'HIGH',
    lastUpdated: '3h ago',
    department: 'L1 Support',
    date: '2024-03-14',
  },
  {
    id: 'TK-9023',
    subject: 'Product Issue with Legion Pro overheating under sustained workload',
    customer: 'Acme Corp',
    status: 'PENDING',
    priority: 'MEDIUM',
    lastUpdated: '1h ago',
    department: 'L1 Support',
    date: '2024-03-13',
  },
  {
    id: 'TK-9022',
    subject: 'Billing Inquiry for bulk AMC license package',
    customer: 'Globex Inc',
    status: 'PENDING',
    priority: 'MEDIUM',
    lastUpdated: '1h ago',
    department: 'Billing',
    date: '2024-03-13',
  },
  {
    id: 'TK-9010',
    subject: 'Feature Request by Enterprise clients for fleet firmware automation',
    customer: 'Globex Inc',
    status: 'PENDING',
    priority: 'MEDIUM',
    lastUpdated: '1h ago',
    department: 'Enterprise',
    date: '2024-03-13',
  },
  {
    id: 'TK-9014',
    subject: 'Billing Inquiry on ThinkStation P620 custom configuration',
    customer: 'Globex Inc',
    status: 'RESOLVED',
    priority: 'LOW',
    lastUpdated: '1h ago',
    department: 'Billing',
    date: '2024-03-12',
  },
  {
    id: 'TK-9013',
    subject: 'Feature Request by Yoga 9i users to enable haptic feedback presets',
    customer: 'Soylent Corp',
    status: 'RESOLVED',
    priority: 'LOW',
    lastUpdated: '1h ago',
    department: 'L2 Technical',
    date: '2024-03-12',
  },
  {
    id: 'TK-9012',
    subject: 'Product Issue on ThinkPad L14 secure boot keys mismatch',
    customer: 'Globex Inc',
    status: 'RESOLVED',
    priority: 'LOW',
    lastUpdated: '1h ago',
    department: 'L1 Support',
    date: '2024-03-12',
  },
  {
    id: 'TK-9015',
    subject: 'Billing Inquiry for enterprise support dispatch excess invoice',
    customer: 'Globex Inc',
    status: 'PENDING',
    priority: 'MEDIUM',
    lastUpdated: '1h ago',
    department: 'Billing',
    date: '2024-03-11',
  },
  {
    id: 'TK-9016',
    subject: 'Product Issue with Premier Support dispatch delays in EU',
    customer: 'Acme Corp',
    status: 'RESOLVED',
    priority: 'LOW',
    lastUpdated: '3h ago',
    department: 'Enterprise',
    date: '2024-03-11',
  },
  {
    id: 'TK-9008',
    subject: 'Product Inquiry on upcoming Lenovo AI Copilot integrations',
    customer: 'Inotech',
    status: 'OPEN',
    priority: 'HIGH',
    lastUpdated: '3m ago',
    department: 'Enterprise',
    date: '2024-03-10',
  },
  {
    id: 'TK-9005',
    subject: 'Lenovo Vantage software suite crashes after Windows update',
    customer: 'Inotech',
    status: 'OPEN',
    priority: 'CRITICAL',
    lastUpdated: '2h ago',
    department: 'L2 Technical',
    date: '2024-03-10',
  },
  {
    id: 'TK-9004',
    subject: 'Legion Toolkit thermal configuration mismatch',
    customer: 'Vertex Group',
    status: 'ESCALATED',
    priority: 'CRITICAL',
    lastUpdated: '5m ago',
    department: 'L2 Technical',
    date: '2024-03-09',
  },
  {
    id: 'TK-9003',
    subject: 'SLA Breach notification - ThinkPad carbon battery swell batch query',
    customer: 'TechNova',
    status: 'ESCALATED',
    priority: 'CRITICAL',
    lastUpdated: '10m ago',
    department: 'Enterprise',
    date: '2024-03-08',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'CID-1001',
    name: 'J. Doe',
    email: 'j.doe@acme.com',
    phone: '+1 (555) 100-1001',
    productsOwned: 3,
    openTickets: 3,
    totalTickets: 5,
    status: 'ACTIVE',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'CID-1002',
    name: 'K. Smith',
    email: 'k.smith@globex.com',
    phone: '+1 (555) 100-1002',
    productsOwned: 2,
    openTickets: 1,
    totalTickets: 3,
    status: 'ACTIVE',
    createdAt: '2024-02-20T10:00:00Z',
  },
  {
    id: 'CID-1003',
    name: 'L. Green',
    email: 'l.green@soylent.com',
    phone: '+1 (555) 100-1003',
    productsOwned: 1,
    openTickets: 0,
    totalTickets: 1,
    status: 'INACTIVE',
    createdAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'CID-1004',
    name: 'L. Green',
    email: 'tech@inotech.com',
    phone: '',
    productsOwned: 1,
    openTickets: 0,
    totalTickets: 0,
    status: 'INACTIVE',
    createdAt: '2024-03-05T10:00:00Z',
  },
  {
    id: 'CID-1005',
    name: 'M. Vance',
    email: 'm.vance@vertex.com',
    phone: '+1 (555) 100-1005',
    productsOwned: 4,
    openTickets: 2,
    totalTickets: 4,
    status: 'ACTIVE',
    createdAt: '2024-02-01T10:00:00Z',
  },
  {
    id: 'CID-1006',
    name: 'A. Stark',
    email: 'a.stark@technova.com',
    phone: '+1 (555) 100-1006',
    productsOwned: 5,
    openTickets: 1,
    totalTickets: 3,
    status: 'ACTIVE',
    createdAt: '2024-01-20T10:00:00Z',
  },
  {
    id: 'CID-1007',
    name: 'P. Parker',
    email: 'p.parker@delta.edu',
    phone: '+1 (555) 100-1007',
    productsOwned: 2,
    openTickets: 1,
    totalTickets: 2,
    status: 'ACTIVE',
    createdAt: '2024-03-15T10:00:00Z',
  },
  {
    id: 'CID-1008',
    name: 'J. Connor',
    email: 'j.connor@cyberdyne.com',
    phone: '+1 (555) 100-1008',
    productsOwned: 8,
    openTickets: 4,
    totalTickets: 6,
    status: 'ACTIVE',
    createdAt: '2024-01-05T10:00:00Z',
  },
  {
    id: 'CID-1009',
    name: 'G. Belson',
    email: 'gavin@hooli.xyz',
    phone: '+1 (555) 100-1009',
    productsOwned: 3,
    openTickets: 0,
    totalTickets: 2,
    status: 'INACTIVE',
    createdAt: '2024-02-10T10:00:00Z',
  },
  {
    id: 'CID-1010',
    name: 'P. Gibbons',
    email: 'pgibbons@initech.com',
    phone: '',
    productsOwned: 2,
    openTickets: 0,
    totalTickets: 0,
    status: 'INACTIVE',
    createdAt: '2024-03-20T10:00:00Z',
  }
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'PID-2001',
    name: 'ThinkPad X1 Carbon',
    model: 'TP-2023-X1',
    description: '14-inch premium business laptop',
    imageUrl: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=400',
    baseWarrantyDays: 365,
    activeCustomers: 4,
    warrantyCoverage: 85,
    amcCoverage: 60,
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'PID-2002',
    name: 'IdeaPad Slim 5',
    model: 'IP-2024-S5',
    description: 'Lightweight everyday laptop',
    imageUrl: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=400',
    baseWarrantyDays: 365,
    activeCustomers: 2,
    warrantyCoverage: 20,
    amcCoverage: 0,
    createdAt: '2024-03-10T10:00:00Z',
  },
  {
    id: 'PID-2003',
    name: 'Legion 5 Pro',
    model: 'LG-2024-5P',
    description: 'High performance gaming laptop',
    imageUrl: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400',
    baseWarrantyDays: 730,
    activeCustomers: 5,
    warrantyCoverage: 90,
    amcCoverage: 75,
    createdAt: '2024-01-05T10:00:00Z',
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'FR-5001',
    customer: 'Acme Corp',
    ticketId: 'TK-9021',
    rating: 5,
    comment: 'Excellent support for Lenovo ThinkPad X1 Carbon. Technical engineer repaired keyboard onsite within 4 hours!',
    date: '2024-03-15',
  },
  {
    id: 'FR-5002',
    customer: 'Globex Inc',
    ticketId: 'TK-9020',
    rating: 5,
    comment: 'Excellent billing support for Lenovo Premier support. Smooth billing and subscription extensions.',
    date: '2024-03-15',
  },
  {
    id: 'FR-5003',
    customer: 'Soylent Corp',
    ticketId: 'TK-9019',
    rating: 2,
    comment: 'Billing dispute took too long. First levels kept routing to regional teams instead of solving it immediately.',
    date: '2024-03-14',
  },
  {
    id: 'FR-5004',
    customer: 'Soylent Corp',
    ticketId: 'TK-9018',
    rating: 2,
    comment: 'Display firmware update query response took 3 business days. Need faster L2 ticketing response times.',
    date: '2024-03-14',
  },
  {
    id: 'FR-5005',
    customer: 'Acme Corp',
    ticketId: 'TK-9017',
    rating: 5,
    comment: 'Superb turnaround on BIOS overclocking patch testing. Engineering team is extremely responsive for Legion.',
    date: '2024-03-14',
  },
  {
    id: 'FR-5006',
    customer: 'Globex Inc',
    ticketId: 'TK-9026',
    rating: 5,
    comment: 'Onsite dispatch of tiny fan parts was flawless. ThinkCentre is running cool again. Highly recommended service.',
    date: '2024-03-14',
  },
  {
    id: 'FR-5007',
    customer: 'Soylent Corp',
    ticketId: 'TK-9019',
    rating: 4,
    comment: 'Excellent technical answers on Lenovo System Update deployment. Smooth SCCM catalog catalogs.',
    date: '2024-03-14',
  },
  {
    id: 'FR-5008',
    customer: 'Globex Inc',
    ticketId: 'TK-9013',
    rating: 2,
    comment: 'Customer dispute about additional repair pricing took too long. Escalated to manager before response received.',
    date: '2024-03-14',
  },
  {
    id: 'FR-5009',
    customer: 'Inotech',
    ticketId: 'TK-9018',
    rating: 5,
    comment: 'Extremely polite engineers. They helped diagnose motherboard issue on Yoga Book over remote link immediately.',
    date: '2024-03-15',
  },
];

export const INITIAL_SLA_RULES: SlaRule[] = [
  {
    id: 'SLA-001',
    ruleName: 'L1 Initial Support Response Time SLA',
    department: 'L1 Support',
    condition: 'Resolution Time',
    priority: 'CRITICAL',
    resolutionTime: '4h',
    notification: '[Notify L1 Team]',
    status: 'ENABLED',
  },
  {
    id: 'SLA-002',
    ruleName: 'L2 Complex Issue Resolution Timeline',
    department: 'L2 Technical',
    condition: 'Resolution Time',
    priority: 'CRITICAL',
    resolutionTime: '4h',
    notification: '[Notify L1 Team]',
    status: 'ENABLED',
  },
  {
    id: 'SLA-003',
    ruleName: 'General L2 Normal Flow Escalation',
    department: 'L2 Technical',
    condition: 'Resolution Time',
    priority: 'HIGH',
    resolutionTime: '24h',
    notification: '[Notify L1 Team]',
    status: 'ENABLED',
  },
  {
    id: 'SLA-004',
    ruleName: 'L1 High Severity Escalate To Lead',
    department: 'L1 Support',
    condition: 'Resolution Time',
    priority: 'HIGH',
    resolutionTime: '24h',
    notification: '[Notify L2 Team]',
    status: 'ENABLED',
  },
  {
    id: 'SLA-005',
    ruleName: 'Billing Disputes Settlement Standard',
    department: 'Billing',
    condition: 'Resolution Time',
    priority: 'MEDIUM',
    resolutionTime: '48h',
    notification: '[Notify L2 Team]',
    status: 'DISABLED',
  },
  {
    id: 'SLA-006',
    ruleName: 'Billing General Query Answering Time',
    department: 'Billing',
    condition: 'Resolution Time',
    priority: 'MEDIUM',
    resolutionTime: '48h',
    notification: '[Notify Billing]',
    status: 'DISABLED',
  },
  {
    id: 'SLA-007',
    ruleName: 'Enterprise VIP Accounts SLA Response Cover',
    department: 'Billing',
    condition: 'Resolution Time',
    priority: 'MEDIUM',
    resolutionTime: '48h',
    notification: '[Notify Billing]',
    status: 'DISABLED',
  },
  {
    id: 'SLA-008',
    ruleName: 'Enterprise Technical Incident Standard SLA',
    department: 'Billing',
    condition: 'Resolution Time',
    priority: 'MEDIUM',
    resolutionTime: '48h',
    notification: '[Notify Billing]',
    status: 'DISABLED',
  },
];
